### PR TITLE
Adding FTP upload option for the ipa file as alternative to app store connect

### PR DESCRIPTION
**Pull request by Joshua-Beatty**
My workflow required me to just get the .ipa file to an ftp server rather then dealing with app store connect or testflight, so I thought I'd make a pull request as it is not that complicated of a change and might be useful to some people.

### CODE REVIEW

**Comment by Shchvova** [comment]
Hey! Thanks for the suggestion. 
Do you require FTP specifically or something else would do?
GitHub Actions have built in capability to upload artifacts.
May be that would work as well?

**Comment by Joshua-Beatty** [comment]
It doesn't necessarily need to be FTP, but that was what I was comfortable with, and as I am not incredibly comfortable with github actions, that is what I implemented. Sorry if my initial statement wasn't clear, but I have made the change already in my fork to work with FTP upload.

Edit: After doing some more research it looks like Artifacts are actually both better and easier for my workflow. I am new to actually contributing to open source, but I think you can close the pull request and I can open a new one if I have a good public facing implementation?

**Comment by Shchvova** [comment]
Hey!
I think this is a great idea but FTP seems little redundant. Try adding upload artifact, than you'll be able to easily download IPA from GitHub (just add last 4 lines to your build.yml):

```yaml
jobs:
  build:
    runs-on: macos-11
    steps:
      - uses: actions/checkout@v2
      - name: Build and Deliver
        run: Util/build.sh
        env:
          CERT_PASSWORD:  ${{ secrets.CertPassword }}
          APPLE_USERNAME: ${{ secrets.AppleUser }}
          APPLE_PASSWORD: ${{ secrets.ApplePassword }}
          APPLE_TEAM_ID:  ${{ secrets.AppleTeamId }}
      - uses: actions/upload-artifact@v2
        with:
          name: IPA
          path: Util/*.ipa
```
Then go to Actions tab in your repository and click on the latest run there. Your IPA would be at the bottom ready to be downloaded

**Comment by Joshua-Beatty** [comment]
Awesome thanks that works great

**Pull request closed without merging**
